version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: mysql_db_FST
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8831:3306"
    volumes:
      - mysql_data_FST:/var/lib/mysql
    networks:
      - weblab_FST

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_FST
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8832:80"
    depends_on:
      - db
    networks:
      - weblab_FST

networks:
  weblab_FST:
    driver: bridge

volumes:
  mysql_data_FST:
    driver: local